### ISSUE TITLE
Test vectors in .json format

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-cpace#12]
Currently, the test vectors are directly added to the draft document.

I suggest adding a dedicated .json file with these vectors, allowing implementers to more easily test their code. This would help shorten the feedback loop.

**Comment by BjoernMHaase** [comment]
Hello Daniel,

I'm a bit confused. Do you suggest to add this .json format to the markdown file, or rather to extend the current test vector generation code such that it outputs, e.g. ANSI-C source code and a .json file?

**Comment by bytemare** [comment]
No, not to the markdown file, but as an extra file that the current POC would output.

A use case: when that file is updated, I can drop it as-is in my implementation without touching the code.
Here's an example of such a file: https://github.com/cfrg/draft-irtf-cfrg-voprf/tree/main/poc/vectors

**Comment by bytemare** [comment]
By the way, it looks like https://github.com/bytemare/draft-irtf-cfrg-cpace/blob/master/poc/test_vectors.sage is not tracked (or at least it's empty).

I would gladly add the JSON functionality if you could share that file :)

**Comment by BjoernMHaase** [comment]
Hello Daniel,Indeed this file was unused. The code for generating testvectors is called CPace_Tesrvectors.sage.Your contribution of a code change for also adding a json file would be great.There is one function that outputs the markdown for one choice of G and H.For a single Json file you might need some prefix in order to distinguish the test vectors for different cipher suites. I have just added a suggestion.For the place for adding your extension maybe have a look at my last commit.--Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 23.01.22, 02:07 schrieb Daniel Bourdrez ***@***.***>:

   
  By the way, it looks like https://github.com/bytemare/draft-irtf-cfrg-cpace/blob/master/poc/test_vectors.sage is not tracked (or at least it's empty). 
  I would gladly add the JSON functionality if you could share that file :)

**Comment by BjoernMHaase** [comment]
Hy bytemare,

I am just coming back to your suggestion.

My idea of how to add test vectors was to first create a python dictionary in each "json-supporting" component of the test vector generation code and export the dictionary as a single .json file.

The topic is only that it might not be automatic if one wants to link the different .json files to the corresponding sections in the text.

**Comment by BjoernMHaase** [comment]
There are new both, json test vectors in the text body itself and a separate JSON test vector file in the repo generated by the reference implementation code.
